name: Deploy to Firebase

on:
  push:
    branches:
      - main      # deploys to staging
      - production # deploys to production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install Dependencies
        run: npm install
      
      - name: Deploy to Staging
        if: github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STAGING }}'
          projectId: createher-fest-website-staging
          channelId: live
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
      
      - name: Deploy to Production
        if: github.ref == 'refs/heads/production'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: createher-fest-website
          channelId: live
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks